### ISSUE TITLE
Citation style with CSL

### ISSUE THREAD

**Issue by jobindj** [shyamd/mkdocs-bibtex#4]
Great plugin here!

Is it possible to change the citation style, for example, by specifying the CSL style file in the .yml? Would be a good feature to have!

Thank you!
Jobin

**Comment by shyamd** [comment]
Hi Jobindj, 

This uses `pybtex` to all the bibtex heavy lifting. Unfortunately, that doesn't support using CSL style files to control the output. You're welcome to submit a patch that enables this directly to `pybtex` or to this repo.

**Comment by jobindj** [comment]
Thank you, @shyamd

**Comment by alexvoronov** [comment]
@jobindj : I am also looking for ways to use CSL styles for citations. I found a workaround: it is possible to use pandoc to add citations, before running mkdocs. 

Suppose you have a file with citations (`[@AuthorYear]` elements) in file `docs/publications-EDITME.md`, and bibliography in `refs.bib`. The following command will create a new file `docs/publications.md` with fully-formatted citations according to CSL file:
```shell
pandoc docs/publications-EDITME.md --bibliography refs.bib -o docs/publications.md -t markdown-citations --csl csl/chicago-syllabus.csl
```
More background on StackOverflow [here](https://stackoverflow.com/a/20935176/13738764), [here](https://stackoverflow.com/a/43679877/13738764), and [here](https://tex.stackexchange.com/a/435037).

I also found that [citeproc-py](https://github.com/brechtm/citeproc-py) can handle both CSL and Bibtex bibliographies, I'll see if I can make it to work instead of pybitex.

**Comment by alexvoronov** [comment]
Actually, I realized that it is possible to call pandoc from inside mkdocs-bibtex plugin, instead of running it separately from the command line. Pandoc might be better option than citeproc-py: citeproc-py appears to be not very robust to "slightly-broken" CSL files, while pandoc handles those CSL files without problem.

There are Python wrappers for pandoc: [pypandoc](https://github.com/bebraw/pypandoc) and [pyandoc](https://github.com/applecrazy/pyandoc). Both wrappers require pandoc and pandoc-citeproc to be installed on the system - an extra dependency. Citeproc-py, on the other hand, is pure Python.

**Comment by jobindj** [comment]
Thanks for sharing, @alexvoronov! I will give this a try 👍

**Comment by shyamd** [comment]
I'm more than happy to accept a PR to switch to `pypandoc`. `pyandoc` looks like it might not be maintained anymore
